TSMAPIDIR=/opt/tivoli/tsm/client/api/bin64/sample
TSMLIB=-lApiTSM64
CC=gcc
CFLAGS=-g -W -Wall -O -I$(TSMAPIDIR)
LDFLAGS=

FILES=tsmpipe.c


all:		tsmpipe

tsmpipe:	$(FILES:.c=.o)
	$(CC) $(CFLAGS) $(LDFLAGS) -o $@ $(FILES:.c=.o) $(TSMLIB) -lm

clean:
	rm tsmpipe *.o
