TSMAPIDIR=/opt/tivoli/tsm/client/api/bin64
TSMLIB=-lApiTSM64
CC=gcc
CFLAGS=-g -W -Wall -O -I$(TSMAPIDIR)/sample
LDFLAGS=-L$(TSMAPIDIR) -Wl,-rpath $(TSMAPIDIR)

FILES=tsmpipe.c


all:		tsmpipe

tsmpipe:	$(FILES:.c=.o)
	$(CC) $(CFLAGS) $(LDFLAGS) -o $@ $(FILES:.c=.o) $(TSMLIB) -lm

clean:
	rm tsmpipe *.o
